# configs/phdos_decoder.yaml
train:
  num_epochs: 100
  lr: 1.0e-4
  log_dir: ./logs/regression
  checkpoint_dir: ./checkpoints/regression
  test_result_path: ./results/test_results.csv
  
model:
  output_size: 64
